# Generated by Django 5.2.6 on 2025-09-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor_remove_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('treated', 'Treated')], default='scheduled', max_length=10),
        ),
    ]
