# Generated by Django 5.2.6 on 2025-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_prescription_pdf_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescription_qr',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
