# Generated by Django 5.2.6 on 2025-09-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_prescription_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medicines',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
