# Generated by Django 5.2.6 on 2025-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_medicines_appointment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
